version: '1'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
    ports:
      - "8010:8010"
    environment:
      - DB_URL=postgresql+psycopg2://cool-user:cool123@db:5432/my-cool-service
      - SECRET_KEY=t1g_nLtx?Pui(p&)R*_dM!UGs-qIb<5C
      - OPA_URL=https://localhost:8181/v1/data/authz
      - TOKEN_URL=https://localhost:8010/api/v1/auth/token
    depends_on:
      - db
      - opa # Add OPA as a dependency for the app service
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: cool-user
      POSTGRES_PASSWORD: cool123
      POSTGRES_DB: my-cool-service
  opa:
    image: openpolicyagent/opa:edge-rootless
    ports:
      - "8181:8181"
    environment:
      - SECRET_KEY=t1g_nLtx?Pui(p&)R*_dM!UGs-qIb<5C
    volumes:
      - ./authz:/authz
      - ./certs/opa:/certs:ro
    command: ["run", "--server", "--log-level", "info", "--ignore=.*", "--tls-cert-file", "/certs/public.crt",
              "--tls-private-key-file", "/certs/private.key", "/authz"]
