version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db:db
    ports:
      - "8010:8010"
    environment:
      - DB_URL=postgresql+psycopg2://user:password@db:5432/auto_cart
    depends_on:
      - db
    command: >
      sh -c "sleep 10 && make run"
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: my-cool-service